### ISSUE TITLE
How to add a new document?

### ISSUE THREAD

**Issue by upeng** [wuyumin/easydoc#1]
1. easydoc -init   √
2. create a new md file such as test.md   √
3. easydoc build  √

**there is no test.html after build........** It seems that build action is not working...
can you describe more details for easydoc, especially for create a new document

**Comment by wuyumin** [comment]
@upeng easydoc -build miss horizontal line -?

**Comment by upeng** [comment]
@wuyumin Sorry, make a mistake in this issue, I use easydoc -build in cmd in fact, but it's still not working

**Comment by wuyumin** [comment]
@upeng 看你的github有中文，可以用中文说吧。目前版本1.x所有创建的md文件都要在src文件夹下，需要在SUMMARY.md使用链接说明需要把这个文件生成网页。新版本开发中，会更自由编写，不用这么限制。

**Comment by upeng** [comment]
@wuyumin ^_^尴尬了， SUMMARY.md中新增了一行  `- [Test](test.md)`  ，手误在中括号和小括号中间多了一个空格，我说怎么一直build不出test.html，真是抱歉啊！对我们程序员而言，这是个很棒的文档管理工具，多谢多谢~

**Comment by wuyumin** [comment]
@upeng 解决问题就好，按markdown语法。欢迎推荐给朋友使用。
