### ISSUE TITLE
Chinese garbled（中文乱码）

### ISSUE THREAD

**Issue by k1195453766** [wuyumin/easydoc#3]
![image](https://user-images.githubusercontent.com/45040711/65397835-d73f2600-dde5-11e9-8a48-e5f22125e60e.png)

If the menu configured in config is confused in Chinese, how can I solve this problem?（在config中配置的菜单如果是中文会出现乱码，请问这个怎么解决？）

**Comment by wuyumin** [comment]
配置文件请使用utf-8编码
